apiVersion: v1
kind: Secret
metadata:
  name: argo-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Kamaroth92/argo_demo_repo.git
  password: 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
  username: random-username